### ISSUE TITLE
What is JDE0?

### ISSUE THREAD

**Issue by aloisdg** [GoodOlClint/Astronomy#1]
Hello,

I am playing with meeus algorithm for a small project. I dont understand what is [JDE0](https://github.com/GoodOlClint/Astronomy/blob/master/Equinox.cs#L80). Can you explain it to me? Thank you.

Also, are you the original developer of the google code project "meeus"?

Cheers,

**Comment by GoodOlClint** [comment]
Wow, somehow I missed this question for two years!
JDE means "Julian Ephemeris Day" JDE0 should be written with a subscript zero, but it basically means "First stab at calculating the JDE" In Meeus' book (second edition) you can find the data used in table 27.A

Yes, I wrote the old Google Code project, was trying to teach myself C# at the time and this seemed like a really good way to get started.

**Comment by aloisdg** [comment]
Alright thank you :)
